// Generate the review receipt only after the bounded checks have passed.
import assert from 'node:assert/strict';
import {readFile,writeFile,readdir,open,stat} from 'node:fs/promises';
import {createReadStream} from 'node:fs';
import {createHash} from 'node:crypto';
const local='.local/station-detail',art='artifacts/station-detail/east-square',candidate=`${local}/candidate`;
const json=async p=>JSON.parse(await readFile(p,'utf8'));
async function hash(path){const h=createHash('sha256');for await(const chunk of createReadStream(path))h.update(chunk);return h.digest('hex');}
async function glb(path){const f=await open(path,'r'),h=Buffer.alloc(20);await f.read(h,0,20,0);const b=Buffer.alloc(h.readUInt32LE(12));await f.read(b,0,b.length,20);await f.close();const g=JSON.parse(b.toString());let triangles=0,batches=0;for(const m of g.meshes)for(const p of m.primitives){batches++;triangles+=(p.indices!==undefined?g.accessors[p.indices].count:g.accessors[p.attributes.POSITION].count)/3;}return {bytes:(await stat(path)).size,triangles,batches,materials:g.materials.length,textures:g.textures?.length??0};}
const spec=await json('web/station/east-square/spec.json'),checks={};
for(const name of ['support','geometry-parity','preservation','native','scoring']){checks[name]=await json(`${art}/${name}.json`);assert.equal(checks[name].status,'pass',name);}
const before=await json(`${art}/before/result.json`),after=await json(`${art}/after/result.json`);
assert.deepEqual(before.errors,[]);assert.deepEqual(after.errors,[]);assert.ok([...before.shots,...after.shots].every(s=>s.ready),'All captures remain connected');assert.equal(before.shots.length,4);assert.equal(after.shots.length,4);
for(let i=0;i<3;i++){
 const b=before.shots[i],a=after.shots[i];assert.equal(a.phase,'Aim');assert.equal(a.robotVisible,false);
 assert.ok(Math.hypot(...['x','y','z'].map(k=>a.feet[k]-b.feet[k]))<.03,'Matched player feet');assert.ok(Math.abs(a.yaw-b.yaw)<.01,'Matched heading');
 assert.ok(Math.hypot(...a.camera.position.map((v,j)=>v-b.camera.position[j]))<.08,'Matched camera');
}
const fingerprints={};
for(const p of ['art-source/atrium/KyotoAtrium.blend','runtime/station-layout.json',`${candidate}/east-square.blend`,`${candidate}/east-square.glb`,`${candidate}/assembled.blend`,`${candidate}/station-layout.json`,`${candidate}/collision-proposal.json`,`${candidate}/browser/atrium.glb`,`${candidate}/browser/station.json`,`${candidate}/browser/atrium-detail.glb`,`${candidate}/browser/atrium-detail.json`,'/opt/boxhaven/workers/waypoint-timing-20260908/KyotoPhysicsWorker_Data/Managed/Assembly-CSharp.dll'])fingerprints[p]=await hash(p);
for(const dir of ['web/station/east-square','web/tests'])for(const name of await readdir(dir)){if((dir.endsWith('east-square')||name.startsWith('east-square-'))&&/\.(py|mjs|md|json)$/.test(name))fingerprints[`${dir}/${name}`]=await hash(`${dir}/${name}`);}
for(const stage of ['before','after'])for(const f of ['wide.png','tree-close.png','globe-close.png','inspection.webm','result.json'])fingerprints[`${art}/${stage}/${f}`]=await hash(`${art}/${stage}/${f}`);
assert.equal(before.layout,fingerprints['runtime/station-layout.json']);
const layout=fingerprints[`${candidate}/station-layout.json`];assert.equal(after.layout,layout);assert.equal(checks.native.layout,layout);assert.equal(checks.scoring.layout,layout);
assert.equal((await json(`${candidate}/browser/station.json`)).layoutSha256,layout);assert.equal((await json(`${candidate}/browser/atrium-detail.json`)).sourceLayoutSha256,layout);
const audit=await json(`${candidate}/browser/atrium-export.json`);assert.equal(audit.sourceSha256,fingerprints[`${candidate}/assembled.blend`]);assert.equal(audit.layoutSha256,layout);
const build=await json(`${local}/preview/web/public/browser-build.json`);for(const f of ['atrium.glb','station.json','atrium-detail.glb','atrium-detail.json'])assert.equal(build.files[`web/public/assets/${f}`].sha256,fingerprints[`${candidate}/browser/${f}`]);
for(const c of checks.native.checks.filter(c=>c.result)){assert.equal(c.result.layout,layout);assert.equal(c.result.physics,checks.scoring.physics);}
const oldCost=await glb('web/public/assets/atrium.glb'),newCost=await glb(`${candidate}/browser/atrium.glb`),delta=Object.fromEntries(Object.keys(oldCost).map(k=>[k,newCost[k]-oldCost[k]]));assert.ok(delta.triangles<=spec.budget.triangles);assert.ok(delta.batches<=spec.budget.batches);assert.equal(delta.textures,0);
const quantile=(a,q)=>[...a].sort((a,b)=>a-b)[Math.floor((a.length-1)*q)];
const timing=s=>s.shots.slice(0,3).map((v,i)=>({view:i,medianMs:quantile(v.render.frameMs,.5),p99Ms:quantile(v.render.frameMs,.99),calls:v.render.calls,triangles:v.render.triangles}));
const receipt={task:'K027',status:'candidate-ready-for-review',preview:'http://127.0.0.1:4283 (isolated local service; existing public proxy preserved)',references:[spec.areaSource,spec.reference,spec.map],season:spec.season,provenance:spec.provenance,candidate,layout,fingerprints,cost:{before:oldCost,after:newCost,delta},checks:{supportSamples:checks.support.supportedBaseSamples,actualSupportedBaseVertices:checks.support.supportedActualBaseVertices,geometryMeshes:checks['geometry-parity'].checks.length,preservation:'pass',native:'pass',scoring:'pass',matchedBrowserViews:3,browserErrors:after.errors,buildWeb:'pass on staged candidate'},softwareTiming:{renderer:after.renderer,before:timing(before),after:timing(after)},commands:['KYOTO_WORKER_EXECUTABLE=/opt/boxhaven/workers/waypoint-timing-20260908/KyotoPhysicsWorker.x86_64 npm run dev -- 4283 (baseline only)','node web/station/east-square/rebuild.mjs','node web/station/east-square/verify-runtime.mjs','python3 web/tests/east-square-support.py','blender -b --python web/station/east-square/build.py',`blender -b --python tools/export_browser_art.py -- --source ${candidate}/assembled.blend --layout ${candidate}/station-layout.json --output ${candidate}/browser`,`blender -b --python tools/build_atrium_detail.py -- --layout ${candidate}/station-layout.json --output ${candidate}/browser --source-output ${candidate}/hardware`,'node web/station/east-square/preview.mjs','node web/tests/east-square-geometry.mjs','node web/tests/east-square-preservation.mjs','node web/tests/east-square-native.mjs',`KYOTO_TEST_ORIGIN=http://127.0.0.1:4283 KYOTO_TEST_OUTPUT=${art}/scoring.json npm run test:runtime`,'K027_STAGE=before node web/tests/east-square-browser.mjs (baseline server)','K027_STAGE=after node web/tests/east-square-browser.mjs','node web/station/east-square/receipt.mjs'],limitations:['Dimensions and placements are inferred; coordinator resolves K029 integration.','Dormant-season tree; exact species/photo date unknown.','Tiny twigs and buds are visual only; substantial structure uses exact mesh contacts.','Linux capture-window software timings are not a warmed benchmark or hardware/Mac/Metal performance validation.','Inherited missing macOS font references appear in source load logs; retained exported mesh geometry is preserved.'],cleanup:'Keep final layer, scratch assembled candidate, proposal, before/after captures and compact receipts; generated assets/research/DB/logs remain uncommitted. No deployment or release publication.'};
await writeFile(`${art}/cost.json`,JSON.stringify(receipt.cost,null,2));await writeFile(`${local}/receipt.json`,JSON.stringify(receipt,null,2));
console.log('PASS receipt: matching layout/worker/assets, three matched views, native checks and bounded costs');
