// Compact review receipt; outputs remain ignored.
import{readFile,writeFile}from'node:fs/promises';import{createHash}from'node:crypto';
const base='.local/station-detail',sha=async p=>createHash('sha256').update(await readFile(p)).digest('hex');
const assembly=JSON.parse(await readFile(`${base}/candidate/verification.json`)),native=JSON.parse(await readFile(`${base}/evidence/native-final-acceptance.json`)),runtime=JSON.parse(await readFile(`${base}/evidence/runtime.json`)),scoring=JSON.parse(await readFile(`${base}/evidence/receiving-score.json`)),browser=JSON.parse(await readFile(`${base}/evidence/gameplay/browser.json`)),gameplay=JSON.parse(await readFile(`${base}/evidence/gameplay/browser.json`));
const files=['web/levels/build-konbini.py','web/levels/konbini-registration.json','web/station/heart-in/fixtures.py',`${base}/layer/WestExitHeartIn.blend`,`${base}/layer/konbini.glb`,`${base}/layer/colliders.json`,`${base}/candidate/KyotoAtrium.blend`,`${base}/candidate/station-layout.json`,`${base}/candidate/browser/atrium.glb`,`${base}/candidate/browser/station.json`,`${base}/candidate/browser/atrium-detail.glb`,`${base}/candidate/browser/atrium-detail.json`];
const hashes={};for(const path of files)hashes[path]=await sha(path);
const frames=browser.evidence.at(-1).state.render.frameMs.slice().sort((a,b)=>a-b);
const receipt={task:'K025',status:'candidate-ready-for-review',deployment:false,preview:'http://127.0.0.1:4281',branch:'fleet/heart-in-20260908',layout:assembly.layout,workerAssemblySha256:await sha('/opt/boxhaven/workers/waypoint-timing-20260908/KyotoPhysicsWorker_Data/Managed/Assembly-CSharp.dll'),references:JSON.parse(await readFile('web/levels/konbini-registration.json')).evidence,hashes,checks:{visualColliderParity:'layer/audit.json',clearance:'layer/clearance.json',assembly:assembly.status,native:native.status,entryScore:scoring.shot.result.score,replayParity:scoring.replayScoreParity,runtime:runtime.status,browserErrors:browser.errors,gameplayErrors:gameplay.errors,gameplayScore:gameplay.shot?.result?.score,buildWeb:'pass',typecheck:'pass',unitTests:'pass'},cost:assembly.delta,softwareRender:{viewport:[960,640],renderer:browser.renderer,frameSamples:frames.length,medianMs:frames[Math.floor(frames.length*.5)],p99Ms:frames[Math.min(frames.length-1,Math.floor(frames.length*.99))]},limitations:['Inferred 2F registration and authored interior, not surveyed shelving.','Original packaging is simplified geometry; reference photographs are not shipped.','Linux SwiftShader evidence does not establish Mac/Metal hardware performance.','Standalone layer and collision proposal require coordinator integration and asset revision; no release/deployment.','Main Blender export wrote complete verified assets but stalled during teardown; process terminated after export receipt was written.'],reproduce:'web/station/heart-in/README.md'};
await writeFile(`${base}/receipt.json`,JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify({status:receipt.status,layout:receipt.layout,cost:receipt.cost}));
