import { chromium } from 'playwright';
import { mkdir,readFile,writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const out='artifacts/phase3/browser-final';await mkdir(out,{recursive:true});const starters=JSON.parse(await readFile('web/starter-challenges.json','utf8'));
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist','--use-angle=metal']});
const context=await browser.newContext({viewport:{width:1440,height:1000},recordVideo:{dir:out,size:{width:1280,height:888}}}),page=await context.newPage(),errors=[],events=[],milestones=[];let latest,received;
page.on('pageerror',e=>errors.push(e.message));page.on('crash',()=>errors.push('Browser page crashed'));page.on('websocket',ws=>ws.on('framereceived',e=>{try{const m=JSON.parse(String(e.payload));if(m.type==='state'){latest=m;received=performance.now();}if(['result','error'].includes(m.type))events.push(m);}catch{}}));
const state=()=>page.evaluate(()=>window.kyotoState),clock=()=>latest.stationTime+(performance.now()-received)/1000;
async function mark(name){milestones.push({name,elapsed:(Date.now()-started)/1000,state:await state()});await page.screenshot({path:`${out}/${String(milestones.length).padStart(2,'0')}-${name}.png`});console.log('Session',name,Math.round((Date.now()-started)/1000)+'s');}
async function axis(axis,target){await page.locator('canvas').focus();const begin=Date.now();await page.keyboard.down('ShiftLeft');while(Date.now()-begin<18000){const delta=target-(await state()).feet[axis];if(Math.abs(delta)<.09)break;const key=axis==='x'?(delta>0?'w':'s'):(delta>0?'a':'d');await page.keyboard.down(key);await page.waitForTimeout(Math.min(650,Math.max(35,Math.abs(delta)/4.2*1000)));await page.keyboard.up(key);await page.waitForTimeout(100);}await page.keyboard.up('ShiftLeft');assert.ok(Math.abs((await state()).feet[axis]-target)<.2);}
async function play(c){await page.getByRole('button',{name:c.name,exact:true}).click();await page.waitForFunction(id=>window.kyotoState?.challenge?.id===id,c.id);await page.locator('#use-hint').click();await page.waitForTimeout(200);await page.locator('canvas').focus();if(c.hint.period){const h=c.hint,target=h.releasePhase+Math.ceil((clock()+h.holdMs/1000+.4-h.releasePhase)/h.period)*h.period;await page.waitForTimeout(Math.max(0,(target-.14-h.holdMs/1000-clock())*1000));}await page.keyboard.down('Space');await page.waitForTimeout(c.hint.holdMs);await page.keyboard.up('Space');await page.waitForFunction(()=>window.kyotoState?.phase==='Flight');await page.waitForTimeout(800);await page.mouse.move(870,420);await page.mouse.down({button:'right'});await page.mouse.move(970,435,{steps:8});await page.mouse.up({button:'right'});await page.waitForFunction(()=>window.kyotoState?.phase==='Result',null,{timeout:40000});await mark(c.id);}
let started;
try{
 await page.goto('http://127.0.0.1:4173');await page.waitForFunction(()=>window.kyotoState?.ready,null,{timeout:120000});started=Date.now();
 await page.evaluate(()=>{window.acceptanceFrames=[];let last=performance.now();function sample(t){window.acceptanceFrames.push(t-last);last=t;if(window.acceptanceFrames.length<40000)requestAnimationFrame(sample);}requestAnimationFrame(sample);});
 await page.getByRole('button',{name:'First Bank',exact:true}).click();await page.waitForFunction(()=>window.kyotoState?.challenge?.id==='atrium-first-bank');await page.locator('#use-hint').click();await page.locator('#explore').click();await page.waitForFunction(()=>!window.kyotoState?.challenge);
 await axis('x',17.8);await axis('z',4.65);await axis('x',30);assert.ok((await state()).feet.y>5.45);await mark('first-landing');await axis('x',17.8);assert.ok((await state()).feet.y<.1);await mark('stairs-return');
 for(const c of starters)await play(c);
 // Replay remains useful even when a timing attempt misses: view a saved best.
 await page.locator('.score-row').first().click();await page.waitForFunction(()=>window.kyotoState?.mode==='replay');await page.locator('#replay-speed').selectOption('0.5');await page.locator('#replay-scrub').focus();await page.keyboard.press('Home');await page.locator('#replay-play').click();await page.waitForTimeout(12000);await mark('slow-replay');await page.locator('#replay-scrub').focus();await page.keyboard.press('End');await page.mouse.move(900,450);await page.mouse.down({button:'right'});await page.mouse.move(650,430,{steps:15});await page.mouse.up({button:'right'});await mark('replay-orbit');await page.locator('#close-replay').click();
 while(Date.now()-started<300000){await play(starters[(milestones.length)%2]);await page.locator('.score-row').first().click();await page.waitForFunction(()=>window.kyotoState?.mode==='replay');await page.waitForTimeout(Math.min(15000,Math.max(0,300000-(Date.now()-started))));await page.locator('#close-replay').click();}
 const frames=await page.evaluate(()=>window.acceptanceFrames),elapsed=(Date.now()-started)/1000,sorted=[...frames].sort((a,b)=>a-b),percentile=p=>sorted[Math.min(sorted.length-1,Math.floor(sorted.length*p))];
 const performanceReport={elapsedSeconds:elapsed,renderedFrames:frames.length,averageFps:frames.length/elapsed,medianFrameMs:percentile(.5),p95FrameMs:percentile(.95),p99FrameMs:percentile(.99),maxFrameMs:sorted.at(-1),stallsOver250ms:frames.filter(t=>t>250).length,startupMs:(await state()).startupMs};
 assert.ok(elapsed>=300);assert.ok(performanceReport.averageFps>=30);assert.ok(performanceReport.p95FrameMs<40);assert.ok(performanceReport.stallsOver250ms<=2);assert.deepEqual(errors,[]);assert.deepEqual(events.filter(e=>e.type==='error'),[]);
 await mark('complete');await writeFile(`${out}/result.json`,JSON.stringify({status:'pass',scope:'One integrated five-minute browser session with DOM traversal, challenge throws, orbit, saved boards and replay',headless:true,viewport:{width:1440,height:1000},renderer:'Chrome ANGLE Metal, pixel ratio 1, authored atrium',performance:performanceReport,milestones,results:events.filter(e=>e.type==='result').map(e=>({attempt:e.attempt,challenge:e.challenge?.name,success:e.success,score:e.score,duration:e.duration})),errors},null,2));console.log('PASS final session',JSON.stringify(performanceReport));
}catch(error){await page.screenshot({path:`${out}/failure.png`}).catch(()=>{});await writeFile(`${out}/result.json`,JSON.stringify({status:'fail',error:String(error),milestones,events:events.filter(e=>e.type!=='result'),errors},null,2));throw error;}finally{const video=page.video();await context.close();if(video)await writeFile(`${out}/video-path.txt`,await video.path());await browser.close();}
