import {chromium} from 'playwright';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
const out=process.env.EVIDENCE_DIR||'.local/fleet/timing';await mkdir(out,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_EXECUTABLE||'/usr/bin/google-chrome',args:['--no-sandbox','--use-angle=gl','--enable-webgl','--ignore-gpu-blocklist']});
const context=await browser.newContext({viewport:{width:1440,height:900},deviceScaleFactor:.25,recordVideo:{dir:out,size:{width:1440,height:900}}});const page=await context.newPage();page.setDefaultTimeout(120000);const arrivals=[];
await page.addInitScript(()=>{let value;window.timingSamples=[];Object.defineProperty(window,'kyotoState',{get:()=>value,set:s=>{value=s;window.timingSamples.push({now:performance.now(),time:s.renderTime,phase:s.phase,feet:s.feet,renderFeet:s.renderFeet,camera:s.camera.position,target:s.camera.target,alpha:s.renderAlpha,frameDt:s.frameDt,step:s.escalatorStep,stage:window.timingStage});if(window.timingSamples.length>5000)window.timingSamples.shift();}});});
if(process.env.TIMELINE_SOURCE)await page.route('**/game.js',async route=>{let body=await readFile(process.env.TIMELINE_SOURCE,'utf8');body=body.replace('renderTime:timeline.time','escalatorStep:Array.from(scene.children.find(o=>o.children[0]?.isInstancedMesh)?.children[0].instanceMatrix.array.slice(12,15)||[]),renderFeet:avatars.get(p?.id)?.group.position.toArray(),renderAlpha:alpha,frameDt:rawDt,renderTime:timeline.time');await route.fulfill({contentType:'text/javascript',body});});
let packet=0,lastDue=0,jitter=false;
await page.routeWebSocket('**',client=>{const server=client.connectToServer();server.onMessage(message=>{let m;try{m=JSON.parse(String(message));}catch{}const now=Date.now();if(m?.type==='state'){arrivals.push({now,time:m.stationTime});packet++;}const due=Math.max(lastDue,now+(jitter&&packet%6<3?120:0));lastDue=due;setTimeout(()=>{try{client.send(message);}catch{}},due-now);});});
try{
 await page.goto(process.env.KYOTO_TEST_URL||'http://127.0.0.1:4273');await page.waitForFunction(()=>window.kyotoState?.ready,null,{timeout:300000});await page.locator('canvas').focus();
 console.log('ready');await page.evaluate(()=>{window.timingSamples=[];window.timingStage='steady';});await page.keyboard.down('KeyW');await page.waitForTimeout(4000);await page.keyboard.up('KeyW');await page.waitForTimeout(1000);
 await page.screenshot({scale:'css',path:`${out}/walk.png`});jitter=true;await page.evaluate(()=>window.timingStage='delayed-wall');await page.keyboard.down('KeyW');await page.keyboard.down('ShiftLeft');await page.waitForTimeout(14000);await page.keyboard.up('KeyW');await page.keyboard.up('ShiftLeft');await page.waitForTimeout(1000);
 await page.evaluate(()=>window.timingStage='lateral-resize');await page.keyboard.down('KeyA');await page.waitForTimeout(1500);await page.keyboard.up('KeyA');await page.setViewportSize({width:1000,height:700});await page.keyboard.down('KeyS');await page.waitForTimeout(2000);await page.keyboard.up('KeyS');await page.waitForTimeout(1000);await page.screenshot({scale:'css',path:`${out}/stop.png`});
 const samples=await page.evaluate(()=>window.timingSamples);await writeFile(`${out}/timing.json`,JSON.stringify({source:process.env.TIMELINE_SOURCE||'current',arrivals,samples},null,2));console.log('Captured actual walking, stops, wall approach, lateral/backward input and viewport/network pacing variation');
}finally{await context.close();await browser.close();}
