import assert from 'node:assert/strict';
import {PerspectiveCamera,Vector3} from 'three';
import {FlyCamera} from '../public/fly-camera.js';
import {designGeometry} from '../public/design-geometry.js';
const source=new PerspectiveCamera();source.position.set(0,10,0);source.lookAt(0,10,-20);
const saved=source.clone(),fly=new FlyCamera(source);fly.enter(source);
for(let i=0;i<10;i++)fly.move(new Set(['KeyW']),.1);
assert.ok(Math.abs(fly.camera.position.z+18)<1e-6);
fly.enter(source);for(let i=0;i<10;i++)fly.move(new Set(['KeyW','ShiftLeft']),.1);
assert.ok(Math.abs(fly.camera.position.z+60)<1e-6);
fly.enter(source);for(let i=0;i<10;i++)fly.move(new Set(['KeyW','KeyD']),.1);
assert.ok(Math.abs(fly.camera.position.distanceTo(source.position)-18)<1e-6,'Diagonal speed is normalized');
fly.look(250,-140);const direction=fly.camera.getWorldDirection(new Vector3()),before=fly.camera.position.clone();fly.move(new Set(['KeyW']),.1);
assert.ok(fly.camera.position.clone().sub(before).normalize().dot(direction)>.9999,'Forward follows the mouse view, including pitch');
assert.deepEqual(source.position,saved.position);assert.deepEqual(source.quaternion.toArray(),saved.quaternion.toArray(),'Scouting cannot alter the robot camera');
fly.leave();const stopped=fly.camera.position.clone();fly.move(new Set(['KeyW']),.1);assert.deepEqual(stopped,fly.camera.position);
const disk={center:{x:0,y:0,z:0},radius:.5,surface:'floor'},course={start:disk,goal:disk,waypoints:[],scoring:'waypoint-v3'};
assert.equal(designGeometry(course),designGeometry({...course,start:{...disk,normal:{x:0,y:1,z:0}}}));
assert.notEqual(designGeometry(course),designGeometry({...course,goal:{...disk,radius:.6}}));
console.log('PASS free-camera speed, boost, normalized movement, mouse direction, saved camera isolation and recorded geometry comparison');
