import assert from 'node:assert/strict';
import {Store} from '../store.ts';
import {Competition} from '../competition.ts';
import {celebrationProfile} from '../public/celebration.js';
import {replayIdFromPath,replayURL} from '../public/replay-links.js';
const s=new Store(':memory:');
try{
 const c={id:'ranking-test',revision:1,creator:'station',name:'Ranking test',layout:'layout',physics:'physics',start:{center:{x:0,y:0,z:0},radius:1,surface:'floor'},goal:{center:{x:2,y:0,z:0},radius:1,surface:'floor'}};s.saveChallenge(c);
 const players=Array.from({length:11},(_,i)=>{const guest=s.guest();s.rename(guest.id,`Player ${i+1}`);return guest;});
 const result=(attempt,guest,score,duration=10)=>({type:'result',attempt,id:guest.id,challenge:c,score,success:true,surfaces:1,duration,poses:[],playerName:guest.name,character:'don'});
 players.slice(0,10).forEach((p,i)=>s.saveResult(result(`old-${i}`,p,10000-i*500),'animation'));
 const shot=result('new',players[10],9600);s.saveResult(shot,'animation');
 assert.equal(shot.standings.rank,2);
 assert.equal(shot.standings.before.length,10);assert.equal(shot.standings.after.length,10);
 assert.equal(shot.standings.before[9].guest,players[9].id);assert.ok(!shot.standings.after.some(r=>r.guest===players[9].id));
 assert.deepEqual(s.replay('new').standings,JSON.parse(JSON.stringify(shot.standings)),'Rank movement is saved atomically with the replay');
 const ownBest=result('better',players[5],11000);s.saveResult(ownBest,'animation');assert.equal(ownBest.standings.rank,1);assert.equal(ownBest.standings.after.filter(r=>r.guest===players[5].id).length,2,'The player keeps both qualifying shots');
 const worse=result('worse',players[5],8000);s.saveResult(worse,'animation');assert.equal(worse.standings.rank,8,'A lower personal score can still enter the top ten');assert.equal(worse.standings.after.filter(r=>r.guest===players[5].id).length,3);
 const faster=result('faster-tie',players[5],11000,9);s.saveResult(faster,'animation');assert.equal(faster.standings.rank,1,'A faster equal score ranks ahead of the old best');assert.ok(faster.standings.after.some(r=>r.attempt==='better'));
 const same=result('same-tie',players[5],11000,9);s.saveResult(same,'animation');assert.equal(same.standings.rank,2,'Both equal scores remain, with the earlier attempt first');
 const last=result('outside-ten',players[9],1);s.saveResult(last,'animation');assert.equal(last.standings.rank,16);
 const miss=result('zero',players[9],0);s.saveResult(miss,'animation');assert.equal(miss.standings.after.length,10);assert.equal(miss.standings.rank,null);
 const competition=new Competition(s,{send(){}},()=>{});competition.layout='layout';competition.physics='physics';const member={id:'session',guest:players[0],selected:null,restoring:false,selecting:false};
 await competition.command(member,{type:'charge',layout:'layout',physics:'physics',character:'koma'});
 await assert.rejects(competition.command(member,{type:'charge',layout:'layout',physics:'physics',character:'don'}),/already active/);assert.equal(member.attemptPresentation.character,'koma','A rejected duplicate charge cannot change the saved robot');
 const snapshot=s.replay('new');s.rename(players[10].id,'New name');assert.deepEqual(s.replay('new'),snapshot,'Renaming does not mutate an original replay');
 assert.ok(!JSON.stringify(snapshot).includes(players[10].token));assert.equal(snapshot.character,'don');
 const duplicate={...shot,score:999999};assert.equal(s.saveResult(duplicate,'animation'),false);assert.equal(s.replay('new').score,9600);
 const dominated={...c,id:'one-player-board'};s.saveChallenge(dominated);
 for(let i=0;i<12;i++)s.saveResult({...result(`dominant-${i}`,players[0],20000+i),challenge:dominated},'animation');
 const board=s.leaderboard(dominated);assert.equal(board.length,10);assert.ok(board.every(r=>r.guest===players[0].id));
 assert.deepEqual(board.map(r=>r.attempt),Array.from({length:10},(_,i)=>`dominant-${11-i}`),'One player can fill every slot with distinct attempts');
 assert.ok(s.replay('dominant-0'),'An attempt falling below the top ten remains shareable');
 assert.equal(s.personalBest(dominated,players[0].id),20011);assert.equal(s.personalBest(c,players[9].id),5500,'Personal best includes scores below the displayed board');
 const tied={...c,id:'tie-board'};s.saveChallenge(tied);
 for(const id of ['tie-z','tie-b','tie-a'])s.saveResult({...result(id,players[0],20000),challenge:tied},'animation');
 s.db.prepare("UPDATE attempts SET accepted=CASE id WHEN 'tie-z' THEN 1 ELSE 2 END WHERE challenge=?").run(tied.id);
 assert.deepEqual(s.leaderboard(tied).map(r=>r.attempt),['tie-z','tie-a','tie-b'],'Acceptance time then attempt ID breaks exact ties without deduplication');
 assert.deepEqual(['tie-z','tie-a','tie-b'].map(id=>s.attemptRank(tied,id)),[1,2,3],'Full ranks use the leaderboard tie breakers');
 const crowded={...c,id:'crowded-board'};s.saveChallenge(crowded);
 for(let i=0;i<249;i++)s.saveResult({...result(`crowded-${i}`,players[0],1000+i),challenge:crowded},'animation');
 const distant={...result('rank-250',players[1],100),challenge:crowded};s.saveResult(distant,'animation');
 assert.equal(distant.standings.rank,250,'Rank counts every shot, including repeated players, beyond the displayed ten');
 assert.equal(distant.standings.before.length,10);assert.equal(distant.standings.after.length,10);
 assert.ok(!distant.standings.after.some(r=>r.attempt===distant.attempt));
 assert.equal(s.replay(distant.attempt).standings.rank,250,'The off-board placement is saved with its replay');
 s.saveResult({...result('later-shot',players[0],2000),challenge:crowded},'animation');
 assert.equal(s.attemptRank(crowded,distant.attempt),251);assert.equal(s.replay(distant.attempt).standings.rank,250,'Later shots do not rewrite the original placement');
 assert.equal(s.attemptRank(c,distant.attempt),null,'Ranks are scoped to the course');
 assert.equal(s.attemptRank({...crowded,revision:2},distant.attempt),null,'Ranks are scoped to the revision');
 assert.equal(s.attemptRank(c,'zero'),null);assert.equal(s.attemptRank(c,'missing'),null);
 for(let i=0;i<9;i++)s.saveResult({...result(`tie-leader-${i}`,players[0],30000+i),challenge:tied},'animation');
 assert.deepEqual(['tie-z','tie-a','tie-b'].map(id=>s.attemptRank(tied,id)),[10,11,12],'Exact ties straddling the top-ten cutoff keep deterministic ranks');
 assert.equal(replayIdFromPath('/replay/abc-123_'), 'abc-123_');assert.equal(replayIdFromPath('/replay/%2f'),null);assert.equal(replayIdFromPath('/replay/abc/nested'),null);assert.equal(replayURL('abc-123','https://kyotobounce.com'),'https://kyotobounce.com/replay/abc-123');
 const profiles=[1,100000,1000000,5000000,20000000].map(score=>celebrationProfile({score,saved:true}));assert.deepEqual(profiles.map(p=>p.tier),[1,2,3,4,5]);
 assert.equal(celebrationProfile({saved:true,score:1,standings:{rank:1,before:[1,2,3]}}).tier,5);
 assert.equal(celebrationProfile({saved:true,score:20000000,breakdown:{outcome:'forfeit'}}).tier,0);
 console.log('PASS repeated-player top-ten insertion/ejection, total domination, independent ties, immutable replay presentation, public URLs and five celebration tiers');
}finally{s.close();}
