// UI-only fixtures. No native contact or final-score claims are made by this test.
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const out=resolve(process.env.KYOTO_EVIDENCE||'artifacts/phase3/waypoint-ui');await mkdir(out,{recursive:true});
const fixture=`import * as THREE from 'three';import {competitionUI} from './competition.js';import {challengeBriefing} from './briefing.js';import {ballHeat} from './ball-heat.js';
const scene=new THREE.Scene(),renderer=new THREE.WebGLRenderer({canvas:document.querySelector('canvas')}),camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.01,500);renderer.setSize(innerWidth,innerHeight);scene.background=new THREE.Color(0x182638);scene.add(new THREE.AmbientLight(0xffffff,2));
const ball=new THREE.Mesh(new THREE.SphereGeometry(.023),new THREE.MeshStandardMaterial({color:0xf1673d})),trail=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial());scene.add(ball,trail);const heat=ballHeat({scene,ball,trail});
document.getElementById('loading').hidden=true;window.sent=[];let phase='Aim';const sound={cue(){}};const ui=competitionUI({scene,sound,send:(type,p)=>sent.push({type,...p}),cancel(){},notice(){},getGuestId:()=> 'test',getLiveTime:()=>0,getPhase:()=>phase,resetView(){},overview:c=>brief.open(c)});const brief=challengeBriefing({renderer,onStart(){},onOpen(){},isReady:()=>true});
window.fixture={ui,scene,brief,heat,ball,renderBrief:()=>{brief.update(camera,.016);renderer.render(scene,camera);},setPhase:p=>phase=p,step:()=>ui.update(.016),heatFrame:(score,time=1,mode='play',reduced=false)=>{ball.visible=true;heat.update({score,time,attempt:'fixture',mode},.016,'Flight',reduced);camera.position.set(.2,.15,.35);camera.lookAt(0,.05,0);renderer.render(scene,camera);return heat.state;}};window.fixtureReady=true;`;
const server=createServer(async(req,res)=>{try{const pathname=new URL(req.url,'http://localhost').pathname;let path=pathname==='/'?'web/public/index.html':pathname==='/fixture.js'?null:pathname.startsWith('/vendor/three/')?'node_modules/three/'+pathname.slice(14):'web/public'+pathname;let data=path?await readFile(path):fixture;if(pathname==='/')data=String(data).replace('/game.js','/fixture.js');res.setHeader('Content-Type',pathname.endsWith('.js')?'text/javascript':pathname.endsWith('.css')?'text/css':'text/html');res.end(data);}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist','--use-angle=metal']});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error(e.message);});page.on('console',m=>{if(m.type()==='error')console.error(m.text());});
try{
 await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForFunction(()=>window.fixtureReady,null,{timeout:15000});console.log('fixture loaded');
 await page.locator('#new-challenge').click();console.log('editor open');await page.locator('#challenge-name').fill('Fixture chain');await page.locator('#has-destination').uncheck();
 const disk={center:{x:0,y:0,z:0},radius:.75,surface:'floor'};
 async function place(button,slot,d){await page.locator(button).click();await page.evaluate(()=>fixture.ui.pointer({}, {origin:{x:0,y:3,z:0},direction:{x:0,y:-1,z:0}}));assert.equal((await page.evaluate(()=>sent.at(-1))).slot,slot);await page.evaluate(({slot,disk})=>fixture.ui.message({type:'placement',slot,disk}),{slot,disk:d});}
 // A canceled, delayed reply must drain before another request can own its slot.
 await page.locator('#place-start').click();await page.evaluate(()=>fixture.ui.pointer({}, {origin:{x:99,y:3,z:0},direction:{x:0,y:-1,z:0}}));const pendingCount=await page.evaluate(()=>sent.filter(m=>m.type==='place').length);
 await page.locator('#place-start').click();await page.evaluate(()=>fixture.ui.pointer({}, {origin:{x:0,y:3,z:0},direction:{x:0,y:-1,z:0}}));assert.equal(await page.evaluate(()=>sent.filter(m=>m.type==='place').length),pendingCount,'same-slot replacement waits for canceled reply');
 await page.evaluate(disk=>fixture.ui.message({type:'placement',slot:'start',disk:{...disk,center:{x:99,y:0,z:0}}}),disk);assert.equal(await page.evaluate(()=>fixture.ui.state.draft.start),null,'late canceled disk never attaches to new placement');
 await place('#place-start','start',disk);
 for(const [i,normal]of [{x:0,y:1,z:0},{x:1,y:0,z:0},{x:0,y:-1,z:0}].entries())await place('#add-waypoint','waypoint',{...disk,center:{x:i*3,y:i*2,z:0},normal,surface:['floor','wall','ceiling'][i]});
 assert.equal(await page.locator('.waypoint-row').count(),3);
 const orientation=await page.evaluate(()=>fixture.scene.getObjectByName('waypoint-targets').children.map(o=>({normal:new (o.position.constructor)(0,0,1).applyQuaternion(o.quaternion).toArray(),position:o.position.toArray()})));assert.ok(orientation[1].normal[0]>.99);assert.ok(orientation[2].normal[1]<-.99);
 await page.locator('.waypoint-row').nth(1).locator('button').first().click();await page.locator('#waypoint-radius').fill('1');await page.locator('#waypoint-radius').dispatchEvent('input');await page.locator('.waypoint-row').last().getByRole('button',{name:'Remove waypoint 3'}).click();
 await page.screenshot({path:out+'/00-editor.png'});await page.locator('#save-challenge').click();const save=await page.evaluate(()=>sent.at(-1));assert.equal(save.scoring,'waypoint-v2');assert.equal(save.goal,null);assert.equal(save.waypoints.length,2);assert.equal(save.waypoints[1].radius,1);assert.equal(new Set(save.waypoints.map(w=>w.id)).size,2);assert.deepEqual(save.waypoints[1].normal,{x:1,y:0,z:0});
 const course={...save,id:'fixture',revision:1,creator:'test',order:0};await page.evaluate(c=>{fixture.ui.message({type:'saved-challenge',challenge:c});fixture.ui.message({type:'session',challenge:c});fixture.brief.open(c);},course);
 // Open/update through a proper camera so null-goal route framing is exercised.
 await page.evaluate(()=>fixture.renderBrief());
 assert.equal(await page.locator('#map-goal').isVisible(),false);assert.match(await page.locator('#briefing-rule').textContent(),/2 OPTIONAL/);await page.screenshot({path:out+'/01-no-goal-briefing.png'});await page.locator('#briefing-play').click();
 const score={version:'waypoint-v2',total:310000,potential:99999999,waypointCount:2,waypointIds:save.waypoints.map(w=>w.id),waypointHits:[],waypointBase:30000,waypointMultiplier:4,destinationReached:false,destinationBonus:0,styleBanks:2,bankMultiplier:3.0625};
 await page.evaluate(score=>{fixture.setPhase('Result');fixture.ui.message({type:'result',attempt:'fixture',score:score.total,saved:false,success:true,breakdown:score});fixture.step();},score);assert.match(await page.locator('#result-rank').textContent(),/WAYPOINTS BANKED/);assert.match(await page.locator('#result-breakdown').textContent(),/points stay yours/);assert.match(await page.locator('#waypoint-progress').textContent(),/NEXT ×4/);
 await page.evaluate(({course,score})=>{fixture.ui.message({type:'replay',replay:{attempt:'r',challenge:course,score:score.total,surfaces:2,duration:3,chargeTime:0,releaseTime:1,scoreFrames:[{t:0,score:{...score,total:0,waypointCount:0,waypointIds:[],waypointMultiplier:1}},{t:2,score}],poses:[{t:0,p:{x:0,y:1,z:0},q:{x:0,y:0,z:0,w:1}},{t:3,p:{x:1,y:0,z:0},q:{x:0,y:0,z:0,w:1}}],thrower:{id:'p',power:.1}}});fixture.step();},{course,score});
 await page.locator('#replay-scrub').fill('3');await page.locator('#replay-scrub').dispatchEvent('input');await page.evaluate(()=>fixture.step());assert.equal(await page.evaluate(()=>fixture.ui.scorePresentation().score.waypointCount),2);
 await page.locator('#replay-scrub').fill('-1');await page.locator('#replay-scrub').dispatchEvent('input');await page.evaluate(()=>fixture.step());assert.equal(await page.evaluate(()=>fixture.ui.scorePresentation().score),null,'scrubbing before shot removes collected state');await page.locator('#close-replay').click();
 await page.locator('#edit-challenge').click();await page.locator('#has-destination').check();await place('#place-goal','goal',{...disk,center:{x:8,y:0,z:0},radius:1.25});await page.locator('#save-challenge').click();assert.equal((await page.evaluate(()=>sent.at(-1))).goal.center.x,8,'editor saves one destination beside existing waypoints');
 await page.locator('#challenge-scoring').selectOption('combo-v6');assert.equal(await page.locator('#waypoint-editor').isVisible(),false);await page.locator('#save-challenge').click();assert.equal((await page.evaluate(()=>sent.at(-1))).scoring,'combo-v6');assert.equal((await page.evaluate(()=>sent.at(-1))).waypoints.length,0);
 await page.locator('#close-editor').click();
 await page.evaluate(()=>{fixture.ui.dismissResult();document.querySelector('#competition').hidden=true;document.querySelector('#notice').hidden=true;fixture.scene.getObjectByName('waypoint-targets').visible=false;for(const group of fixture.scene.children)if(group.isGroup)group.visible=false;});
 const tiers=[];for(const [i,total]of [100000,1000000,10000000].entries()){tiers.push(await page.evaluate(({score,total})=>fixture.heatFrame({...score,total}),{score,total}));await page.screenshot({path:out+`/0${i+2}-heat-tier-${i+1}.png`});}assert.deepEqual(tiers.map(t=>t.tier),[1,2,3]);
 await page.evaluate(()=>fixture.heat.reset());assert.equal(await page.evaluate(()=>fixture.heat.state.tier),0);
 for(const version of ['combo-v6']){await page.evaluate(({course,version})=>{fixture.ui.message({type:'session',challenge:{...course,scoring:version,goal:{center:{x:8,y:0,z:0},radius:1,surface:'floor'},waypoints:[]}});fixture.ui.message({type:'result',attempt:version,score:17500,success:true,saved:false,breakdown:{version,outcome:'perfect',base:10000,styleBanks:1,bankMultiplier:1.75,landingMultiplier:1,total:17500,potential:17500}});fixture.step();},{course,version});assert.equal(await page.locator('#result-rank').textContent(),'PERFECT LANDING');assert.match(await page.locator('#score-guide').textContent(),/landing accuracy/);}
 assert.deepEqual(errors,[]);await writeFile(out+'/result.json',JSON.stringify({status:'pass',scope:'Browser fixture UI only; native acceptance separate',save,orientation,tiers,errors},null,2));console.log('PASS browser editor, oriented markers, no-goal briefing, destination-miss result, next-award label and heat tiers');
}finally{await browser.close();server.close();}
