// Compact review evidence bound to exact source, visual, collision and worker bytes.
import {readFile,writeFile,readdir,stat} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {resolve} from 'node:path';
import {execFileSync} from 'node:child_process';
const root=resolve('artifacts/station-detail/plaza-landmarks'),c=root+'/candidate';
const json=async p=>JSON.parse(await readFile(p,'utf8'));
const file=async p=>({path:p,bytes:(await stat(p)).size,sha256:createHash('sha256').update(await readFile(p)).digest('hex')});
const build=await json(c+'/build.json'),browser=await json(c+'/browser.json'),native=await json(root+'/native.json'),geometry=await json(c+'/geometry-check.json'),scoring=await json(root+'/scoring-runtime.json'),assembly=await json(c+'/browser/assembly.json');
if(browser.partial||native.status!=='pass'||geometry.status!=='pass'||scoring.status!=='pass'||browser.errors.length||browser.consoleErrors.length)throw Error('Acceptance evidence is incomplete or failed');
if(![native.layout,geometry.candidateLayoutSha256,assembly.layoutSha256,...browser.records.map(r=>r.art.sourceLayout)].every(h=>h===build.layoutSha256))throw Error('Evidence layout identities differ');
if(browser.records.length!==9||browser.performancePairs.length!==3)throw Error('Missing views or measurements');
const summary=s=>{const ms=s.map(x=>x.ms).sort((a,b)=>a-b);return {medianMs:(ms[3]+ms[4])/2,p99Ms:ms.at(-1),calls:s.at(-1).calls,triangles:s.at(-1).triangles,samples:s.length};};
const performance=browser.performancePairs.map(p=>{const base=summary(p.layerHidden),candidate=summary(p.candidate);return {view:p.id,layerHidden:base,candidate,delta:{medianMs:candidate.medianMs-base.medianMs,calls:candidate.calls-base.calls,triangles:candidate.triangles-base.triangles}};});
const sources=[];for(const name of await readdir('web/station/plaza-landmarks'))sources.push(await file('web/station/plaza-landmarks/'+name));for(const name of await readdir('web/tests'))if(name.startsWith('plaza-landmarks-'))sources.push(await file('web/tests/'+name));
const artifacts=[];for(const p of ['PlazaLandmarks.blend','AssembledCandidate.blend','plaza-landmarks.glb','collision-proposal.json','station-layout.json','anchors.json','browser/atrium.glb','browser/station.json','browser/atrium-detail.glb','browser/atrium-detail.json','inspection.mp4'])artifacts.push(await file(c+'/'+p));
const receipt={task:'K028',git:{commit:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),branch:execFileSync('git',['branch','--show-current'],{encoding:'utf8'}).trim()},status:'candidate ready for coordinator review',layout:build.layoutSha256,baseLayout:build.baseLayoutSha256,workerAssembly:native.assembly,workerExecutable:await file('/opt/boxhaven/workers/waypoint-timing-20260908/KyotoPhysicsWorker.x86_64'),source:sources,artifacts,references:(await json('web/station/plaza-landmarks/specification.json')).references,checks:{native:native.checks.length,nativeStatus:native.status,geometry:geometry.status,exactMatchedTriangles:geometry.exactMatchedGlbCollisionTriangles,scoring:scoring.status,browserViews:browser.records.length,browserErrors:browser.errors,consoleErrors:browser.consoleErrors,buildWeb:'pass'},renderCost:{method:browser.performanceMethod,renderer:browser.renderer,viewport:[960,640],layerMeshes:build.objects,layerTriangles:build.triangles,layerGlbBytes:build.glbBytes,assembledDownloadDeltaBytes:(await stat(c+'/browser/atrium.glb')).size-(await stat('web/public/assets/atrium.glb')).size,originalTexturePixels:build.texturePixels,textureCountDelta:1,rgbaTextureBytesWithMipmaps:Math.ceil(build.texturePixels*4*4/3),performance},limitations:['Placement and dimensions are inferred, not surveyed.','Inherited station shell does not reconstruct the reference Kyoto Tower vista.','Linux SwiftShader synchronized draw timings are diagnostic only; no Mac/Metal acceptance claim.','Full assembled source inherits the release blend missing macOS Hiragino font warning; browser preserves original base bytes.'],deployment:'none',preview:'http://127.0.0.1:4284 (isolated candidate; existing public proxy untouched)'};
await writeFile('.local/station-detail/receipt.json',JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify({layout:receipt.layout,checks:receipt.checks,renderCost:receipt.renderCost},null,2));
