import { spawn } from 'node:child_process';
import { mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
const unity = process.env.UNITY_EDITOR || '/Applications/Unity/Hub/Editor/6000.3.23f1/Unity.app/Contents/MacOS/Unity';
const linux=process.argv.includes('--linux');
await mkdir('artifacts/phase3/builds', { recursive: true });
const log = resolve(`artifacts/phase3/builds/worker-${new Date().toISOString().replaceAll(':','-')}.log`);
console.log(`Building ${linux?'Linux':'macOS'} native physics worker. Log:`, log);
const child = spawn(unity, ['-batchmode', '-nographics', '-quit', '-buildTarget', linux?'StandaloneLinux64':'StandaloneOSX', '-standaloneBuildSubtarget', linux?'Server':'Player', '-projectPath', resolve('KyotoRicochet'), '-executeMethod', `Kyoto.Editor.BrowserWorkerBuilder.${linux?'BuildLinux':'Build'}`, '-logFile', log], { stdio: 'inherit' });
child.on('error', error => { console.error(error); process.exitCode=1; });
child.on('exit', code => { console.log('Worker build exit:', code); process.exitCode=code ?? 1; });
